# Generated by Django 3.2.16 on 2023-08-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20230801_1948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('created_at',), 'verbose_name': 'комменнтарий', 'verbose_name_plural': 'коменнтарии'},
        ),
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.TextField(verbose_name='Текст коменнтария'),
        ),
    ]
